### ISSUE TITLE
Let glyphsLib take a custom Font class

### ISSUE THREAD

**Issue by adrientetar** [googlefonts/glyphsLib#157]

**Comment by schriftgestalt** [comment]
Is this related with the work started in the class-tree fork?

**Comment by anthrotype** [comment]
I don't think so; it's about letting clients like TruFont pass a custom defcon Font subclass when building UFOs.

**Comment by belluzj** [comment]
It should be possible now, if you use the `glyphsLib.builder.to_ufos` directly and give your own `defcon`-like python module as the argument `ufo_module`. The builder will instantiate the `Font` class (and other classes if needed) from that module. Does that solve the issue?

https://github.com/googlei18n/glyphsLib/blob/master/Lib/glyphsLib/builder/__init__.py#L25-L26

**Comment by anthrotype** [comment]
/cc @adrientetar 

kind of. The problem is here we are expecting other clients to name their defcon subclasses with the same name as the original defcon module.
Which I don't think it's the case for TruFont, where all the defcon's subclasses are prefixed with "T" if I remember well.
But maybe that could be changed in TruFont, I don't think the latter was ever used as a library and its implementation of defcon objects is kind of private.

**Comment by anthrotype** [comment]
An alternative to passing a module instance as a parameter, could be passing a mapping of UFO class names to specific classes... Or maybe even simpler, the caller could make a SimpleNamespace, set attributes on that with the names of the original defcon classes that glyphsLib expects, and pass that object as the "defcon" module. We would just getattr from it and boom it would work.
The problem is actually knowing which classes are needed from that "defcon" module. Maybe it should be documented.

**Comment by adrientetar** [comment]
I could rename the classes but it would probably be confusing... could we use duck typing here? e.g. allow to pass both a module and a dict somehow since a module is essentially a dict. Then you could either give a module or a dict of {"Font": MyFont, ...} etc.

**Comment by anthrotype** [comment]
instead of a dict, you could pass an objects with attributes (that looks like a module), i.e. SimpleNamespace

**Comment by adrientetar** [comment]
Btw with defcon you only need the Font class becaus then you can do font.instantiateGlyph etc. and class names cascade through the object hierarchy but obviously that's not a universal API.

**Comment by adrientetar** [comment]
> instead of a dict, you could pass an object with attributes (that looks like a module), i.e. SimpleNamespace

Yes that would work. The argument could be renamed to ufo_namespace I guess.

**Comment by behdad** [comment]
> An alternative to passing a module instance as a parameter, could be passing a mapping of UFO class names to specific classes... Or maybe even simpler, the caller could make a SimpleNamespace, set attributes on that with the names of the original defcon classes that glyphsLib expects, and pass that object as the "defcon" module. We would just getattr from it and boom it would work.

Or just a degenerate object instance that has .Font, .Glyph, etc set to the actual classes?  I think the current code is alright.

**Comment by behdad** [comment]
> Or just a degenerate object instance that has .Font, .Glyph, etc set to the actual classes? I think the current code is alright.

Err, right, that's SimpleNamespace indeed.  So, no need to getattr, right?

**Comment by anthrotype** [comment]
no need to getattr.

**Comment by belluzj** [comment]
@adrientetar So are you ok with the current solution to this issue?

**Comment by anthrotype** [comment]
the current solution being passing a `ufo_module` argument (defaulting to vanilla defcon) to `builder.to_designspace` or the UFOBuilder constructor, like so

https://github.com/googlei18n/glyphsLib/blob/0a86327a93b3f324f200e35a23f639db4ae58280/Lib/glyphsLib/builder/__init__.py#L57-L62

**Comment by anthrotype** [comment]
I think also the GlyphsBuilder class needs to take an `ufo_module` parameter, because when it is provided with a designspace as in put, it needs to load the UFO sources from the paths provided in the designspace, and right now it is hard-coded to `defcon.Font`:

https://github.com/googlei18n/glyphsLib/blob/60026c83af4d02b23470d770a66868092d97c1f3/Lib/glyphsLib/builder/builders.py#L380-L386

**Comment by belluzj** [comment]
For information, I did that because I thought that in the direction -> Glyphs, it does not matter that `defcon.Font` is used internally, because it's not what `to_glyphs` will produce in the end (it produces a `GSFont`).

Also for now, let's say if you don't want to use `defcon` but rather `ufoLib`, there is the option to fill-in the `source.font` properties before giving the designspace to `to_glyphs`.

Maybe it's still a good idea to add `ufo_module` for convenience, I don't know (you're better placed to judge that if you're testing ufolib :))

**Comment by anthrotype** [comment]
@belluzj ok makes sense, thanks for the clarification.

**Comment by khaledhosny** [comment]
I think all is done here.
