### ISSUE TITLE
Do something about outside open corners

### ISSUE THREAD

**Issue by belluzj** [googlefonts/glyphsLib#255]
When should they be removed?
* keep them in UFO and add an option in ufo2ft to remove them
* remove in UFO (but keep the original path somewhere to round-trip back)

Related:
https://forum.glyphsapp.com/t/how-to-detect-an-outside-open-corner/4117

**Comment by schriftgestalt** [comment]
To decide if the overlap is visible or not, it uses the percentage of the parts of the two segments that are "outside" (both segments are at least 50% inside or one of the two is at least 70% inside).

**Comment by anthrotype** [comment]
Thanks Georg, that's helpful.

**Comment by moyogo** [comment]
Since these are Glyphs only at the moment we can remove them with converting to UFO but it would be useful to add the functionality to UFO for roundtripping.

Say we store the original outline in the lib with a glyphsLib key and restore it on roundtrip if it's still valid, do not it if it isn't any more. Either by hashing it, or recalculating and comparing it.

We might want to unify this with how FontLab VI doors open contours overlaps further down.
