### ISSUE TITLE
error when exporting to UFO and duplicate layers contain background

### ISSUE THREAD

**Issue by alexmyczko** [googlefonts/glyphsLib#588]
```
# glyphs2ufo Inter.glyphs 
Inter Thin: Glyph asterisk, layer Dec 27 18, 16:33: Duplicate glyph layer name
Traceback (most recent call last):
  File "/usr/bin/glyphs2ufo", line 11, in <module>
    load_entry_point('glyphsLib==5.1.4', 'console_scripts', 'glyphs2ufo')()
  File "/usr/lib/python3/dist-packages/glyphsLib/cli.py", line 228, in _glyphs2ufo_entry_point
    return main(args)
  File "/usr/lib/python3/dist-packages/glyphsLib/cli.py", line 189, in main
    return options.func(options)
  File "/usr/lib/python3/dist-packages/glyphsLib/cli.py", line 220, in glyphs2ufo
    ufo_module=__import__(options.ufo_module),
  File "/usr/lib/python3/dist-packages/glyphsLib/__init__.py", line 123, in build_masters
    ufo_module=ufo_module,
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/__init__.py", line 111, in to_designspace
    return builder.designspace
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 260, in designspace
    list(self.masters)  # Make sure that the UFOs are built
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/builders.py", line 223, in masters
    self.to_ufo_glyph(ufo_glyph, layer, layer.parent)
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/glyph.py", line 127, in to_ufo_glyph
    self.to_ufo_glyph_background(ufo_glyph, layer)
  File "/usr/lib/python3/dist-packages/glyphsLib/builder/glyph.py", line 265, in to_ufo_glyph_background
    new_glyph = ufo_layer.newGlyph(glyph.name)
  File "/usr/lib/python3/dist-packages/ufoLib2/objects/layer.py", line 120, in newGlyph
    raise KeyError("glyph %r already exists" % name)
KeyError: "glyph 'asterisk' already exists"
```

Find Inter at https://github.com/rsms/inter

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950099

**Comment by madig** [comment]
Smells like a duplicate layer name. I though this was fixed 🤔

**Comment by alexmyczko** [comment]
trying master

**Comment by madig** [comment]
Go through the layers in the Glyphs file and remove layers with duplicate names.

**Comment by alexmyczko** [comment]
> Go through the layers in the Glyphs file and remove layers with duplicate names.

with glyphsapp?

**Comment by anthrotype** [comment]
we only fixed the issue with duplicate foreground layers (by renaming them in UFO to make them unique); however, if these duplicate layers have also background layers, we still the the error above
https://github.com/googlefonts/glyphsLib/pull/570#issuecomment-577725767

**Comment by anthrotype** [comment]
to recap the issue, Glyphs identifies layers using a UUID, whereas in UFO they are identified by their name (in layercontents.plist) and they must be unique. Sometimes .glyphs sources may contain layers with duplicate name (but distinct UUID). When we export from .glyphs to UFO we need to make their name unique if we want to be able to store them.
Previously, when glyphsLib was using defcon as its UFO backend, we were unknowingly losing data because the layers with duplicate names were being silently overwritten. As we switched to ufoLib2, we now get that error when attempting to add a new glyph with the same name as one that is already present. Glyph layers are stored as .GLIF files with that glyph's name inside a UFO layer with the glyph layer's name (which must be unique).
The fix should be to apply the same deduplication logic that we do for foreground duplicate layers to their associated background layer.

Also note that currently we only support deduplicating the layer names in one direction only; when going back, we don't strip the suffix to restore the original duplicate name.
We may want to do that in the future for better roundtripping.

**Comment by alexmyczko** [comment]
ok the glyphs app exported to ufos, trying them:
http://phd-sid.ethz.ch/debian/fonts-inter/UFO/

**Comment by madig** [comment]
> fontTools.feaLib.error.FeatureLibError: src/Inter-Black Italic.ufo:40:1: "mediumspace-math" is not a glyph in the font, and it can not be split into a range of known glyphs
make[1]: *** [debian/rules:14: override_dh_auto_build] Error 1

You're missing a glyph.

**Comment by alexmyczko** [comment]
I am missing 12 weights of 18

**Comment by madig** [comment]
Are those interpolated? Glyphs is probably not exporting those, you'd need a Designspace. Use glyphs2ufo instead. Maybe clear out all non-master layers first.

**Comment by alexmyczko** [comment]
glyphs2ufo also would fail but I got a manually fixed Inter.glyphs now
