### ISSUE TITLE
Completeness is wasteful

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#673]
In the common case of using glyphsLib to convert to UFO as part of the fontmake pipeline, all of this code is unnecessary:

```
    self.to_ufo_background_image(ufo_glyph, layer)
    self.to_ufo_guidelines(ufo_glyph, layer)
    self.to_ufo_glyph_background(ufo_glyph, layer)
    self.to_ufo_annotations(ufo_glyph, layer)
```

Converting any non-master, non-brace layers is also wasteful.

**Comment by khaledhosny** [comment]
Not only wasteful, Glyphs files might have some garbage there (e.g. layers with duplicate names) that will not be used for anything but will break the build anyway.

**Comment by moyogo** [comment]
Color layers can have the same name if they have the same color. https://github.com/googlefonts/glyphsLib/issues/573

**Comment by simoncozens** [comment]
Incidentally the performance impact of doing less is pretty minimal in the grand scheme of things: https://daltonmaag.github.io/pipeline-perf-tracker/results/

**Comment by madig** [comment]
Profile of fontmake when compiling Noto Sans to a VF from a .glyphs file:

![image](https://user-images.githubusercontent.com/380829/113184639-57e9a880-924d-11eb-8cca-e8b572dafb68.png)

A lot of time is wasted on 1. writing intermediate UFOs to disk because MutatorMath needs that 2. parsing the file.

**Comment by simoncozens** [comment]
Use the new parser.
