### ISSUE TITLE
support for `meta` table needed

### ISSUE THREAD

**Issue by bobh0303** [googlefonts/glyphsLib#693]
ufo2ft [now supports](https://github.com/googlefonts/ufo2ft/pull/509) the `meta` table [defined in UFO3](https://unifiedfontobject.org/versions/ufo3/lib.plist/#publicopentypemeta).  

However, it doesn't look as though glyphsLib supports it yet: I tried round-tripping a UFO to glyphs and back, and the meta table info was removed -- but maybe I did something wrong?

**Comment by moyogo** [comment]
The issue is that `to_glyphs_master_user_data()` skips copying lib key-value pairs to userData when a key starts with `public.`.
https://github.com/googlefonts/glyphsLib/blob/86cbeb56e4c3b26a8c1d5a6fe8de40b3c936b54c/Lib/glyphsLib/builder/user_data.py#L141-L146
https://github.com/googlefonts/glyphsLib/blob/86cbeb56e4c3b26a8c1d5a6fe8de40b3c936b54c/Lib/glyphsLib/builder/user_data.py#L201-L202

The assumption is that these keys will be handled somewhere else, but in this case it never is and ends up not being copied to the Glyphsapp file.

There was a request for it to be supported in Glyphsapp
https://forum.glyphsapp.com/t/feature-request-support-for-public-opentypemeta/9039
Has that been implemented? Maybe in Glyphs3?

**Comment by schriftgestalt** [comment]
The meta table is not supported in Glyphs 3, yet. I’ll have a look. It will most likely be a custom parameter (using a list of dicts with `tag` and `value` as keys.)

**Comment by bobh0303** [comment]
Any progress on this?

FontBakery is now testing the meta table.

**Comment by schriftgestalt** [comment]
Hi

Thanks for the reminder. I’ll have a look.

g

**Comment by schriftgestalt** [comment]
I added support for the meta table. It is stored in a `meta Table` custom parameter (in the font or in instances)
```
{
	name = "meta Table";
	value = (
		{
			data = "de-Latn";
			tag = dlng;
		},
		{
			data = "sr-Cyrl";
			tag = slng;
		}
	);
}
```

**Comment by bobh0303** [comment]
@moyogo Does this provide what you need to add round-trip of meta table data between UFO and Glyphs?

**Comment by schriftgestalt** [comment]
The ufo spec stores the data as a dict but the meta spec explicitly mentions that there could be duplicate tags. So even if that is not useful right now, round-tripping it in a dict doesn't work. And on some point, the order might matter.
