### ISSUE TITLE
Something is amiss with this dependency

### ISSUE THREAD

**Issue by alerque** [googlefonts/glyphsLib#701]
Having inherited packaging duties for a dozen or so Python font related libraries on Arch Linux I'm working my way through cleaning them up. Something is amiss with this one:

https://github.com/googlefonts/glyphsLib/blob/19b26b6af390702302795d9f747aea9fcfcafb5c/setup.cfg#L33

Similar to [this PR on booleanOperations](https://github.com/typemytype/booleanOperations/pull/63) I think deleting this entirely is correct (using setuptools locally shouldn't require it), but unlike on that PR I'm not so confident the rest of the project (CI tooling, other Python build tooling, etc.) is setup to handle it properly if just deleted outright without making other adjustments first so the `bdist` builds keep working.

I'm happy to submit a PR to drop this but first somebody more familiar with the release process should confirm.

**Comment by anthrotype** [comment]
technically it _is_ required, but only if one calls the `setup.py bdist_wheel` command, and setuptools will error out if that's not the case.

However, it's safe to remove `wheel` from setup.cfg's `setup_requires`, because we are pip-installing it manually before calling `bdist_wheel` later on:

https://github.com/googlefonts/glyphsLib/blob/721427629dd30b1f2e4b309b0a9d36fd87e59d18/.github/workflows/ci.yml#L62

The `wheel` build-time dependency is listed in pyproject.toml file:
https://github.com/googlefonts/glyphsLib/blob/721427629dd30b1f2e4b309b0a9d36fd87e59d18/pyproject.toml#L20

pip will use the latter when installing from a source distribution, when creating the temporary build environment where a wheel is first generated, and then unzipped to destination.

I suppose that downstream maintainers of linux distros -- who don't use pip as installer but manage python modules with their own tools -- probably ignore the pyproject.toml file.
