### ISSUE TITLE
Axis mappings are missing in designspace

### ISSUE THREAD

**Issue by jenskutilek** [googlefonts/glyphsLib#714]
It seems that glyphsLib only adds axis mappings from the "Axis Location" custom parameter of masters, but not those of exports. Thus the avar table when building with fontmake/glyphsLib is different than when exporting the VF directly from Glyphs.

**Comment by RosaWagner** [comment]
@jenskutilek gftools and dependencies are using the Axis Mapping in font info to set the AVAR etc. 

Note that it has been implemented to follow the standard .designspace file presentation: so user value on the left, and design values on the right (instead of current display of internal/external coordinates in Glyphs).

So for using fontmake/builder etc. you only need this parameter (and consistent values in the exports settings) — no axis location in master nor instances.

Hope my graph is clear:
<img width="990" alt="Capture d’écran 2021-09-07 à 16 21 15" src="https://user-images.githubusercontent.com/12222436/132362167-707078ae-6581-4273-93bc-a3f07090a506.png">

**Comment by schriftgestalt** [comment]
As far as I can see, the current version is exporting `avar` correctly: the x-axis has the coordinates as used inside the .glyphs file and the y-axis is what the user of the font can set the slider too. (this was broken for some time but is fixed now).
