### ISSUE TITLE
Default feature writers heuristic is baffling

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/glyphsLib#764]
If the Glyphs file does not have a manual `kern` feature, glyphsLib does nothing special, and ufo2ft uses a default list of feature writers, which is

```
        KernFeatureWriter,
        MarkFeatureWriter,
        GdefFeatureWriter,
        CursFeatureWriter,
```

But if the Glyphs file has a manual `kern` feature, glyphsLib writes a `com.github.googlei18n.ufo2ft.featureWriters` lib entry in the designspace file:

https://github.com/googlefonts/glyphsLib/blob/609b1765096b016e7382b1155c4034888a0de878/Lib/glyphsLib/builder/user_data.py#L47-L55

glyphsLib's version of `DEFAULT_FEATURE_WRITERS` contains two writers: `KernFeatureWriter` and `MarkFeatureWriter`.

So an Arabic which has a manual kern feature (even if that feature just says `# Automatic code start`) will lose its cursive positioning feature. That was surprising!

I could fix this by adding more feature writers to glyphsLib's default list, but I don't think that's the right fix. I don't understand why we are we making our own "default" list, which we now have to keep in sync with ufo2ft, when *not doing anything at all* would cause ufo2ft to do the right thing.

**Comment by anthrotype** [comment]
> I don't understand why we are we making our own "default" list, which we now have to keep in sync with ufo2ft

i guess to avoid having to import (and thus depend on) ufo2ft

**Comment by anthrotype** [comment]
good catch though. Let's add the missing writers to glyphsLib's default list of feature writer.

**Comment by anthrotype** [comment]
another reason is explained in the inline comment:

https://github.com/googlefonts/glyphsLib/blob/fb6ba4731258d1d8ffa36ed937ec339695feb28b/Lib/glyphsLib/builder/constants.py#L92-L106

**Comment by anthrotype** [comment]
hm actually that code predates the support for `# Automatic code` insertion marker in ufo2ft.
Currently ufo2ft writers' default "mode" would best be described as "skip if already present or insert at the provided insertion marker". [When the mode is "append" the insertion markers are ignored](https://github.com/googlefonts/ufo2ft/pull/458#issuecomment-779855261) if I'm not mistaken (cc @moyogo):

https://github.com/googlefonts/ufo2ft/blob/0ee84954455cb3f451b32ab8df8509cefe025c72/Lib/ufo2ft/featureWriters/baseFeatureWriter.py#L85-L106

If glyphsLib uses KernFeatureWriter(mode="append") instead of the default "skip" whenever there's a manually written "kern" feature (see `to_designspace_family_user_data`) , then any insertion markers contained therein will _not_ be used, which looks like a bug to me..

**Comment by khaledhosny** [comment]
Perhaps we should add insertion marker (if none is already present) in a place that matches where Glyphs would insert its automatic code, and do away with setting feature writers list?

**Comment by anthrotype** [comment]
@khaledhosny yeah, that would work! If the insertion marker is missing in the manually written `kern`, we add it at the bottom (to achieve the same effect as "append" mode). And we don't modify the default writer list.

@simoncozens could you make a PR?

**Comment by simoncozens** [comment]
This just bit me again, in Noto Sans. I'll take look.

**Comment by simoncozens** [comment]
I just found out that this bug has another, more subtle manifestation.

If there is a manual kern feature, then (prior to fixing this in #849) then our feature writers might not get run, which would include the GDEF feature writer, meaning that mean that GDEF categories might not be correctly set, which may lead to [very confusing layout bugs](https://github.com/notofonts/telugu/issues/13).

I just tried building Noto Sans Telugu before and after 416dcbf, and yep, that's definitely the problem and #849 definitely fixed it.
