### ISSUE TITLE
support for virtual masters

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/glyphsLib#859]
We gonna have more and more fonts with parametric axes. Those axes often affect a part of a glyphset's outlines (ascender, descender, x-heigth, etc). Therefore to be able to do that better while using Glyphs, we are going to need virtual masters which is a feature allowing a better management of design sources.

Doc about virtual masters: https://glyphsapp.com/learn/creating-a-variable-font at section "Optional: add a virtual master".

I made a test case with Rubik. 
[virtual-master.zip](https://github.com/googlefonts/glyphsLib/files/10757339/virtual-master.zip)

The set up is: there is one component that is a line. And it is implemented in each glyphs to create guidelines. 

<img width="205" alt="Capture d’écran 2023-02-16 à 16 10 19" src="https://user-images.githubusercontent.com/12222436/219405150-2699b1b6-9eed-4ea8-a647-d4daebf85b6c.png">

Then I have an axis called "Guideline thickness". This axis only affect that one component. So it would be annoying to duplicate masters in sources for that, we may as well use virtual masters.

<img width="966" alt="Capture d’écran 2023-02-16 à 16 25 06" src="https://user-images.githubusercontent.com/12222436/219410343-4f7fb2d8-7e34-4258-94f2-2faf6615f0c7.png">

These intermediate layers are only in the component glyph.

This is the result when exporting with Glyphs:
https://user-images.githubusercontent.com/12222436/219409640-430e33f2-24fc-4dd7-9e7d-1634777de531.mov

Great stuff.

cc @simoncozens

**Comment by anthrotype** [comment]
Thanks @RosaWagner the test font is very useful.

I have a question for @schriftgestalt about Virtual Masters. A regular master can have an Axis Location custom parameter associated to it, but IIUC a Virtual Master cannot (itself being a font custom parameter), so does that mean for Virtual Masters we have to assume that external (user-space) coordinates == internal design coordinates, and therefore those extra axes along which virtual masters are defined cannot be bended via avar?

**Comment by anthrotype** [comment]
ok well, Axis Mappings can be used in that case

**Comment by schriftgestalt** [comment]
> so does that mean for Virtual Masters we have to assume that external (user-space) coordinates == internal design coordinates, and therefore those extra axes along which virtual masters are defined cannot be bended via avar?

They can be bended with avar. The axes location in the master is bending fvar.  

And "usually"(1) the virtual masters are used for not defined axes and thous they are less restricted in he axis range. Or you use the intended external value directly. 

1) I added that parameter to make be able to add a "ascender height" axis. That only needs deltas in very few glyphs, so a full master would be wasteful.

**Comment by anthrotype** [comment]
@RosaWagner I just made an unexpected discovery. If you add an "Axis Mappings" custom parameter like the following, then virtual masters seem to work even if the "Virtual Master" custom parameter is not actually parsed by the current glyphsLib:

![image](https://github.com/googlefonts/glyphsLib/assets/6939968/c86ddacb-bca2-454b-a7b7-2edf88214839)

The Axis Mappings has to contain mappings for at least the min, default and max values for all the axes, including the new axes only used by the virtual masters. It's ok if internal and external coordinates are the same.
It seems like glyphsLib uses the Axis Mappings if provided to also define an axis min and max values, and that is  essentially also the purpose of the Virtual Master custom parameters, so even if the latter aren't read at the moment, the presence of Axis Mappings is sufficient for glyphsLib and thus fontmake to define an axis min/max wide enough to fit the virtual/intermediate layers. The latter are already being exported by glyphsLib and treated the same as true (non-virtual) intermediate brace layers, the problem with Virtual Master support is that (at least in absence of Axis Mappings) the non-virtual masters alone being all located at the same coordinate (for the axis used exclusively by the virtual masters) and thus they are not sufficient to extend the axis min/max which ends up being == default and thus not variable.
I'll make a PR to support reading the virtual master custom parameters when generating a DS axis min/max and the axis is un-mapped.

You can find the modified test file below:
[virtual-master-2.zip](https://github.com/googlefonts/glyphsLib/files/13297455/virtual-master-2.zip)


Note that I also had to duplicate intermediate layers to all the mixed composite glyphs that use the `_part.line` glyph as component otherwise they would not be decomposed as expected (that distinct bug is tracked in #954).

**Comment by bghryct** [comment]
hey @anthrotype @RosaWagner I'm having trouble replicating this process for a similar project. Any advice would be appreciated. [https://github.com/Afrotype/danfobase](https://github.com/Afrotype/danfobase)

We're trying to have a variable component shape that act as variable "cuts" into a single style.

**Comment by schriftgestalt** [comment]
I had a look at the file. You can remove several things that are not needed. 
- The Weight axis (as you already suspected). 
- The Axis Mapping parameter, as it is not mapping anything
- The first "Virtual Master" (Weight: 700, Shape: 0). This axis position is already defined by the regular master
- The "Variable Font Origin", as you only have one masters.

And the setup of the accents needs cleanup:
- You have stacked accents but most of the mark glyphs do not have a `top` anchor
- The diereiscomb is made form a regular scaled period and one that is rotated 180°. That will lead to misalignments.
- The dotbelowcomb either needs anchors, or you can rotate it by 180°, then it will convert the _top anchor from the dotaccentcomb. 

In general I would recommend to not add all available latin accented glyphs just because it is easy to do. Fix the design first and then add the accented glyphs in smaller batches and properly draw/setup all glyphs. Having a lot empty or wrong glyphs in a font is not helping.
